
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew cairo
brew cmake
brew eigen
brew emacs
brew ffmpeg
brew figlet
brew flac
brew fontconfig
brew freetype
brew fzy
brew gdbm
brew gettext
brew giflib
brew glib
brew gmp
brew gnutls
brew heroku
brew highlight
brew icu4c
brew ilmbase
brew imagemagick
brew jpeg
brew lame
brew libcaca
brew libffi
brew libogg
brew libpng
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libvorbis
brew libyaml
brew lua
brew mad
brew mas
brew nettle
brew node
brew nodebrew
brew numpy
brew opencv@2
brew openexr
brew openssl
brew p11-kit
brew pcre
brew perl
brew pixman
brew pkg-config
brew pyenv
brew python
brew python@2
brew readline
brew ruby
brew sdl2
brew sl
brew sox
brew sqlite
brew toilet
brew tree
brew vim --with-override-system-vi
brew watchman
brew x264
brew xvid
brew xz
brew yarn
brew zsh

tap homebrew/bundle

tap homebrew/cask
cask 1password
cask blender
cask db-browser-for-sqlite
cask emacs
cask hyper
cask macvim
cask qlmarkdown
cask quicklook-csv
cask slack
cask station
cask toggl

tap heroku/brew
brew heroku-node

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask betterzip
cask cyberduck
cask dropbox
cask google-chrome
cask karabiner-elements
cask qlcolorcode
cask qlstephen
cask quicklook-json
cask spear
cask supercollider
cask wireshark

# App Store applications
appstore 406056744 Evernote (7.2.1)
appstore 682658836 GarageBand (10.1.3)
appstore 668208984 GIPHY CAPTURE (4.0)
appstore 408981434 iMovie (10.1.4)
appstore 409183694 Keynote (7.0.5)
appstore 411213048 LadioCast (000012004)
appstore 539883307 LINE (5.8.0)
appstore 441258766 Magnet (2.1.0)
appstore 409203825 Numbers (4.0.5)
appstore 409201541 Pages (6.0.5)
appstore 447513724 SmartConverter (2.4.0)
appstore 1278508951 Trello (2.10.4)
appstore 497799835 Xcode (9.2)
